### ISSUE TITLE
if-watch does not work on windows/WSL2

### ISSUE THREAD

**Issue by rklaehn** [ipfs-rust/if-watch#8]
On the "linux" provided by WSL2 windows, if-watch does not work. It bails out with an OS Error 22 - illegal arguments. Presumably because the API used by if-watch is not supported on the WSL2 flavour of "linux".

It would be useful to get this to work, by using the poll based fallback in all cases where the event based approach is not supported by the operating system.

E.g. this causes this issue in ipfs-embed:
https://github.com/ipfs-rust/ipfs-embed/issues/63

**Comment by dvc94ch** [comment]
would checking if `WSL_DISTRO_NAME` is set work? that way we don't hide errors or have missing bug reports

**Comment by rklaehn** [comment]
> would checking if WSL_DISTRO_NAME is set work? that way we don't hide errors or have missing bug reports

But that means that you have to build for wsl to use wsl, whereas otherwise the binary is basically a normal linux binary, right?

I don't think we want to create a special WSL binary for actyx, for example.

**Comment by dvc94ch** [comment]
no, it dynamically selects the fallback if it detects WSL at runtime
